version: '3.2'

services:
  composer:
    volumes:
    - ./:/app
    image: softonic/composer-rector
    command: composer run test
  dev:
    volumes:
    - ./:/app
    image: webdevops/php-nginx-dev:7.4
